services:
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: sato
            DB_USERNAME: sato
            DB_PASSWORD: sato
        depends_on:
            - db
        command: >
            sh -c "
                php artisan key:generate &&
                php artisan migrate --force &&
                php artisan filament:assets &&
                php artisan octane:frankenphp
            "

    node:
        image: node:22-alpine
        working_dir: /app
        volumes:
            - .:/app
        command: sh -c "npm install && npm run dev -- --host"
        ports:
            - "5173:5173"

    db:
        image: postgres:15
        restart: unless-stopped
        environment:
            POSTGRES_DB: sato
            POSTGRES_USER: sato
            POSTGRES_PASSWORD: sato
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
