# User FrankenPHP image
FROM php:8.3-fpm

# Set working directory
WORKDIR /app

# Install PHP extensions
RUN apt update && apt install -y \
    zip \
    libzip-dev \
    libicu-dev \
    libpq-dev \
    && docker-php-ext-install \
        zip \
        intl \
        pcntl \
        pdo_pgsql \
    && docker-php-ext-enable \
        zip intl pcntl pdo_pgsql \
    && rm -rf /var/lib/apt/lists/*

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Install Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt install -y nodejs

COPY . .

RUN composer install --no-dev --optimize-autoloader

RUN npm install && npm run build

RUN chown -R www-data:www-data storage bootstrap/cache public/build

EXPOSE 9000
